### ISSUE TITLE
RFC: Removing Ruby 1.9.3 and adding Ruby 2.2.4 in cflinuxfs2

### ISSUE THREAD

**Issue by Dannyzen** [cloudfoundry/cflinuxfs2#29]
Hi there,

As you may be aware the cflinuxfs2 stack currently includes Ruby 1.9.3. As support for this version will be sunset [1] on February 24th, 2016 this presents a challenge with our current implementation.

We're happy to conclude that the results of our research found that changing the base Ruby version from 1.9.3 to 2.24 provided a desired level of backwards compatibility. If you’re interested in experimenting with the change, check out the ruby-2.2.4 tag in the cloudfoundry/cflinuxfs2 dockerhub repo [2]. 

Our preference is to make the change to cflinuxfs2 by 3/7/2016. If you have any concerns or feedback please comment on this issue.

[1] - https://www.ruby-lang.org/en/news/2015/12/16/ruby-2-0-0-p648-released/
[2] - https://hub.docker.com/r/cloudfoundry/cflinuxfs2/tags/

**Comment by voelzmo** [comment]
Just out of curiosity: Why is there ruby in the stack at all? Shouldn't every buildpack bring ruby itself if that is necessary? Or is something else running in there which requires ruby?

**Comment by flavorjones** [comment]
@voelzmo Thanks for asking!

The rootfs has carried a Ruby interpreter since the Dawn Of Time™[1]; and we have tried to fulfill a commitment to users that updates to the rootfs will be backwards-compatible if at all possible (which means we generally don't remove any packages; though obviously that may become unsustainable at some point).

Notably, though, Ruby is used relatively widely to implement Buildpacks, and it would perhaps put an undue burden on Buildpack maintainers to have to provide their own version of Ruby in order to bootstrap into, say, a Java application.

[1]: for some definition of the Dawn Of Time for Cloud Foundry

**Comment by voelzmo** [comment]
Thanks @flavorjones for the explanation. Now that I look at the code of the java buildpack, I see why a ruby interpreter is needed :D

**Comment by Dannyzen** [comment]
This has been completed in Stacks [release 1.42.0](https://github.com/cloudfoundry/stacks/releases/tag/1.42.0)
