### ISSUE TITLE
RFC: Adding arbitrary '-dev' bindings

### ISSUE THREAD

**Issue by qnm** [cloudfoundry/cflinuxfs2#37]
Hi all,

My company is investigating using Cloud Foundry, and as part of the research process has noted that some C bindings are not part of the `linuxfs2` image.

I see that a recent request for `python-dev` was rejected, and I'm wondering whether it's worth requesting the addition of `libprotobuf-dev` and `libxapian-dev` or if I should just go down the path of rolling my own?

What are the criteria for inclusion?

Thanks,

 -- Rob

**Comment by flavorjones** [comment]
Hi,

`libpython-dev` isn't included because we believe that python applications are all being staged with the `python-buildpack`, which itself includes this development dependency.

Can you help us understand your use case for `libpython-dev`?

We're very open to adding dependencies to the rootfs, particularly if we have the runtime library but not the development library (and it's not something that's being vendored in the core buildpacks). What libraries did you have in mind? Any besides `libprotobuf-dev` and `libxapian-dev`?

**Comment by qnm** [comment]
> Can you help us understand your use case for libpython-dev?

I don't have one - I misunderstood the reasoning behind excluding it from the build, as per #34.

> What libraries did you have in mind? Any besides libprotobuf-dev and libxapian-dev?

I _think_ I also need the protobuf compiler. Let me get you a complete list, now that I know you're open to adding packages to the base image.

Thanks!

**Comment by jchesterpivotal** [comment]
It's worth noting that while we're open to it in theory, it's a very narrow and stingy gate.

Anything added to the rootfs affects every single app. Because of the wide impact this tends to be a made as a product decision.

**Comment by sesmith177** [comment]
@qnm any update on the complete list of libraries you need?

**Comment by sesmith177** [comment]
@qnm any update on the complete list of libraries you need?

**Comment by qnm** [comment]
@sesmith177 Thanks for getting in touch Sam. At this stage it's unlikely that we'll be looking further into Cloud Foundry, but I will re-open the ticket if and when I need those extra packages! Thanks.
