### ISSUE TITLE
Unneeded config files for removed package?

### ISSUE THREAD

**Issue by danjahner** [cloudfoundry/cflinuxfs2#48]
Is there a reason that we are retaining config files for this package?

https://github.com/cloudfoundry/cflinuxfs2/blob/master/cflinuxfs2/cflinuxfs2_receipt#L319

**Comment by sclevine** [comment]
I think the `rc` is due to some interesting logic around installing the mysql client libs here:
https://github.com/cloudfoundry/cflinuxfs2/blob/master/cflinuxfs2/build/install-packages.sh#L17

We regenerate the stack from scratch every time, so the config isn't really retained from the previous version. We're just retaining the config from the removed packages.

This goes away in cflinuxfs3:
https://github.com/cloudfoundry/cflinuxfs3/blob/master/receipt.cflinuxfs3.x86_64#L343

**Comment by sclevine** [comment]
Actually, kinda looks like we should be including libmariadbclient-dev instead in cflinuxfs3. Prioritized this here: https://www.pivotaltracker.com/story/show/159580190
